//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Storage.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        public int Numder { get; set; }
        public string Name { get; set; }
        public int Unit_of_measurement { get; set; }
        public int Remains { get; set; }
        public int Storage { get; set; }
    
        public virtual Storage Storage1 { get; set; }
        public virtual Unit_of_measurement Unit_of_measurement1 { get; set; }
    }
}
